### PR TITLE
Made it compatible with both python2 and python3

### PR DESCRIPTION
**Pull request by rogst**
Fixed issues with import statements, and bytes/str issues between python 2 and 3.

### CODE REVIEW

**Comment by edvinerikson** [comment]
Thanks :+1:

**Comment by edvinerikson** [comment]
It seems that the tests are failing in 3.5 (see https://github.com/edvinerikson/frostbite-rcon-utils-python/pull/3). What Python version did you try this with?

**Comment by rogst** [comment]
I used python 3.4, but I totally forgot to update the tests to match the changes I did. I will fix that and send you a new pull request.

**Comment by edvinerikson** [comment]
I just merged #3 so it will run the tests against 3.5 in master now.
Thank you for making this change. :)

**Pull request merged**
